---

- name: Prepare system configuration
  hosts: localhost
  gather_facts: no
  become: yes

  tasks:

    - name: Update system settings
      ansible.posix.sysctl:
        name: "{{ item['key'] }}"
        value: "{{ item['value'] }}"
      loop: "{{ system_settings | dict2items }}"
